CREATE TABLE SeatingChart (
    FLOOR_SEAT_SEQ SERIAL PRIMARY KEY,
    FLOOR_NO INT NOT NULL,
    SEAT_NO INT NOT NULL
);

CREATE TABLE Employee (
    EMP_ID VARCHAR(5) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    FLOOR_SEAT_SEQ INT,
    CONSTRAINT fk_seat
        FOREIGN KEY(FLOOR_SEAT_SEQ)
        REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
        ON DELETE SET NULL
);